# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DrawingTaggingPad' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'ChromaColorPicker'
  # Pods for DrawingTaggingPad

  target 'DrawingTaggingPadTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DrawingTaggingPadUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
